### ISSUE TITLE
Is gin-swagger working for go1.15.3?

### ISSUE THREAD

**Issue by singhpratik-cb** [mikkeloscar/gin-swagger#67]
The installation command does not show any errors, 
`go get github.com/mikkeloscar/gin-swagger `

but when i try using `gin-swagger`, it bounces off this error

-bash: gin-swagger: command not found

System:
Mac OS Mojave
go version go1.15.3 darwin/amd64

Can someone please point to me what might be wrong and how can i fix it?

**Comment by mikkeloscar** [comment]
Could it be that `$GOPATH/bin` is not in your path? I believe the default is `$HOME/go/bin` is the binary there?

**Comment by singhpratik-cb** [comment]
Thanks for the direction. Indeed the issue was with the GOPATH. Thanks
